### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by ghost** [zollipaul/prj-rev-bwfs-dasmoto#4]
https://github.com/zollipaul/prj-rev-bwfs-dasmoto/blob/master/dasmotos-arts/index.html#L16

Nice job using an inline tag like `span` to write your price information. Rather than give each `span` the same ID, you should be giving each tag the same _class_ instead. IDs should be used to identify a single element, not a group of elements. 

Using the same class allows you to easily select the all the `span` tags related to pricing and will prevent bugs in the future.

**Comment by zollipaul** [comment]
thanks :)
